/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AbSideDrawer {
        "title": string;
    }
}
declare global {
    interface HTMLAbSideDrawerElement extends Components.AbSideDrawer, HTMLStencilElement {
    }
    var HTMLAbSideDrawerElement: {
        prototype: HTMLAbSideDrawerElement;
        new (): HTMLAbSideDrawerElement;
    };
    interface HTMLElementTagNameMap {
        "ab-side-drawer": HTMLAbSideDrawerElement;
    }
}
declare namespace LocalJSX {
    interface AbSideDrawer {
        "title"?: string;
    }
    interface IntrinsicElements {
        "ab-side-drawer": AbSideDrawer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ab-side-drawer": LocalJSX.AbSideDrawer & JSXBase.HTMLAttributes<HTMLAbSideDrawerElement>;
        }
    }
}
