/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AbAtockPrice {
    }
}
declare global {
    interface HTMLAbAtockPriceElement extends Components.AbAtockPrice, HTMLStencilElement {
    }
    var HTMLAbAtockPriceElement: {
        prototype: HTMLAbAtockPriceElement;
        new (): HTMLAbAtockPriceElement;
    };
    interface HTMLElementTagNameMap {
        "ab-atock-price": HTMLAbAtockPriceElement;
    }
}
declare namespace LocalJSX {
    interface AbAtockPrice {
    }
    interface IntrinsicElements {
        "ab-atock-price": AbAtockPrice;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ab-atock-price": LocalJSX.AbAtockPrice & JSXBase.HTMLAttributes<HTMLAbAtockPriceElement>;
        }
    }
}
